--- 
title: "FSS RDM Pages"
author: "FSW Data Steward"
date: '`r format(Sys.time(), "%d %B %Y")`'
site: bookdown::bookdown_site
documentclass: book
description: |
  These are the RDM Pages for the faculty of Social Sciences.
url: "https://vu-fss.github.io/rdm/"
github-repo: "/vu-fss/rdm"
---


```{r setup, include=FALSE}

library(tidyverse)
library(kableExtra)
library(stringr)
library(knitr)

knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE,
                      fig.align = "center")
Sys.setlocale("LC_TIME", "English")
local({r <- getOption("repos")
       r["CRAN"] <- "https://cloud.r-project.org" 
       options(repos=r)
})

display_more_resources <- T

more_resources <- 
"## FSS RDM Resources
- [Information when starting a new project][fss-getting-started]
- [FSS RDM Guidelines][fss-guidelines-rdm]
- [Data organization][fss-guidelines-organization]
- [Data archiving][fss-guidelines-archiving]
- [RDM FAQ][fss-rdm-faq]
- [Overview of RDM Tools ][fss-rdm-tools]
"

my_list <- list(a = 1, b = 2)

print_more_resources <- function(){
  if (display_more_resources){
    cat(more_resources)
  }
}

```

# Index

This web site contains the latest draft versions of the Research Office's pages on
Research Data Management. The current "official" versions of these pages can be accessed through
the [Social Sciences Getting Started page][fss-getting-started].

## Table of contents

- **Support throughout the Research Cycle**
  1. **Plan & Design**
    - [Content for proposals: Ethics, Privacy, RDM (Koen)](#proposal-content-rdm)
  2. **Starting a new project (Time to Grant)**
    - [Ethics, Data Management and Privacy for new projects](#new-rdm)
  3. **Managing ongoing projects**
    - [Organizing your research data (Koen)](#ongoing-rdm)
  4. **Publishing, and Impact**
    - [Archiving and/or publishing data (Koen)](#completed-rdm)
- **Knowledge and Guidelines**
  - [Templates](#templates)
  - RDM
    - [Data Management Policy](#rdm-policy)
    - [RDM FAQ](#rdm-faq)
    - [RDM Tools](#rdm-tools)
    - [A Guide to FAIR data](#rdm-fair)


<!---
Links
Make sure all links are defined here so that they can be easily updated.
-->

<!-- Faculty Pages -->

[rerc]: https://vu.nl/en/employee/social-sciences-getting-started/research-ethics-review-fss
[self-check]: https://vuletteren.eu.qualtrics.com/jfe/form/SV_6hCj2czIWzboW6V
[fss-rdm-info]: https://vu.nl/en/employee/social-sciences-getting-started/data-management-fss

[fss-archiving]: https://github.com/kleuveld/rdm_pages/blob/fss_rdm_policy/_documents/fss_archiving_guidelines.md
[fss-rdm-faq]: rdm-faq.html
[fss-guidelines-rdm]: fss-guidelines-rdm.html
[fss-guidelines-archiving]: data-archiving.html
[fss-guidelines-organization]: data-organization.html
[fss-rdm-tools]: rdm-tools.html
[fss-getting-started]: https://vu.nl/en/employee/social-sciences-getting-started
[fss-templates]: templates.html
[fss-new-project]: 


<!-- VU-wide Resources -->

[libguide]: https://libguides.vu.nl/rdm
[rds-portal]: https://vu.nl/nl/medewerker/research-data-support
[storage-costs]: https://vu.nl/en/employee/research-data-support/costs-research-en-archiving-storage

[vu-minimal-metadata]: https://github.com/vu-rdm-tech/metadata/blob/main/minimal_metadata_guide.md


[vu-knowledgesecurity]: https://vu.nl/en/employee/onderwijs-en-onderzoeksbeleid/knowledge-security-for-vu-amsterdam-employees
<!---
Rules, regulations and guidelines
-->

[gdpr]: https://gdpr-info.eu
[dsw-guidelines]: https://vunl.sharepoint.com/:b:/s/FSW-OE-ResearchOfficeFSS/EWdu638M90NLpl4itmugiscBvXWSHuQXefay0wYgw9-P3Q?e=ZcakCq
[erc-guidelines]: https://ec.europa.eu/research/participants/data/ref/h2020/other/hi/oa-pilot/h2020-hi-erc-oa-guide_en.pdf
[vu-rdm-policy]: https://libguides.vu.nl/ld.php?content_id=32045526
[nlcoc]: https://doi.org/10.17026/dans-2cj-nvwu
[eucouncilopendata]: https://data.consilium.europa.eu/doc/document/ST-9526-2016-INIT/en/pdf
[fairprinciples]: https://www.go-fair.org/fair-principles/
[fairprinciples-background]: https://www.nature.com/articles/sdata201618
[ABV-guidelines]: https://antropologen.nl/app/uploads/2019/01/guidelines-for-anthropological-research.pdf
[NSV-guidelines]: https://www.nsv-sociologie.nl/?page_id=17
[nkwp-guidelines]: http://politicologie.nl/wp-content/uploads/2021/10/Beroepscode-2008.doc
[aom-guidelines]: https://aom.org/about-aom/governance/ethics/code-of-ethics


<!---
Policy comparions
-->

[fss-coc]: policy-comparisons.html#netherlands-code-of-conduct-for-research-integrity-standards-for-good-research-practices
[fss-vu]: policy-comparisons.html#vu-rdm-policy
[fss-dsw]: policy-comparisons.html#guideline-for-the-archiving-of-academic-research-for-faculties-of-behavioural-and-social-sciences-in-the-netherlands

[fss-fair]: policy-comparisons.html#fair-principles
[fss-abv]: policy-comparisons.html#guidelines-for-anthropological-research-data-management-ethics-and-integrity
[fss-aom]: policy-comparisons.html#academy-of-management-code-of-ethics
[fss-nkwp]: policy-comparisons.html#beroepscode-nederlandse-kring-voor-wetenschap-der-politiek
[fss-nsv]: policy-comparisons.html#beroepscode-nederlandse-sociologische-vereniging

<!-- 
  Tools
-->

[RDS-tools]: https://vu.nl/en/about-vu/more-about/rdm-tools 
[dmponline]: https://dmponline.vu.nl
[storage-finder]: https://vu.nl/en/research/storagefinder
[yoda]: https://yoda.vu.nl

[sdcmicro]: https://sdcpractice.readthedocs.io/en/latest/sdcMicro.html
[amnesia]: https://amnesia.openaire.eu/
[storage-finder]: https://vu.nl/en/research/storagefinder
[cryptomator]: https://cryptomator.org/
[research drive]: https://services.vu.nl/esc?id=kb_article&sysparm_article=KB0012856





<!-- Templates 
find there in: Teams/Webpages research/datamanagement/files
-->

[privacystatement_nl]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/ESBLrBcDrLhLpzfiVI8nHmUB76Deu6chNA3xehbSeOnemw?e=IKm8Qb
[privacystatement_en]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/EYTq4TISYv5ElJJzSRxC7IcByRFwKCzlMy8EAiOvBXpZmw?e=QLnXfB
[informedconsent_nl]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/ERBn_xahKvlLkDUK-U_tftEBotu01tkqAGJEmek6QaW7bA?e=RgpKjO
[informedconsent_en]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/ESqv_KBkeEJPnzIe4JwM7YUBVUY_etYwMWDodDm2Yq5pFQ?e=9a3rCQ

[pre-dpia]: https://vunl.sharepoint.com/:x:/s/FSW-OE-ResearchOfficeFSS/EX1MJyVi1h9MrRAbuzKnLyoBosb4QYSLPwoulyQgX8-qTA?e=mDpvYU
[dpia]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/EXTSY7ytMZdAk1p5D3BhCRoBbLxyyljF8MFRd2P4LfIjjg?e=Qmzhhk

[liber-dmps]: https://libereurope.eu/working-group/research-data-management/plans/
[dmponline-public]: https://dmponline.vu.nl/public_plans


[datasharingstatement]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/EaPobOoyWvtOraUROLEo6IoBCSbezaf-QGQYmiK1wazN3g?e=tyOI7T


<!-- Contacts -->

[rdmsupport]: mailto:RDM@vu.nl 
[datasteward]: mailto:k.leuveld@vu.nl
[privacychampion]: mailto:k.leuveld@vu.nl